import {
  AvatarItem,
  BudgetItem,
  DailyTask,
  FinancialTransaction,
  OnboardingAnswers,
  SavingsGoal,
  UserProfile,
  UserStats,
} from "@/lib/types";

export const demoProfile: UserProfile = {
  id: "demo-user-1",
  username: "fajr_striver",
  fullName: "Ahmad Ramadhan",
  timezone: "Asia/Jakarta",
  userType: "mahasiswa",
  onboardingCompleted: true,
};

export const demoStats: UserStats = {
  level: 14,
  rank: "D",
  totalExp: 2120,
  currentExp: 220,
  nextLevelExp: 800,
  coins: 480,
  prayerStreak: 9,
  fullQuestStreak: 4,
};

export const demoTasks: DailyTask[] = [
  {
    id: "q1",
    name: "Shalat Subuh",
    category: "deen",
    taskType: "mandatory",
    expReward: 20,
    coinReward: 0,
    status: "completed",
  },
  {
    id: "q2",
    name: "Shalat Dzuhur",
    category: "deen",
    taskType: "mandatory",
    expReward: 20,
    coinReward: 0,
    status: "completed",
  },
  {
    id: "q3",
    name: "Shalat Ashar",
    category: "deen",
    taskType: "mandatory",
    expReward: 20,
    coinReward: 0,
    status: "pending",
  },
  {
    id: "q4",
    name: "Shalat Maghrib",
    category: "deen",
    taskType: "mandatory",
    expReward: 20,
    coinReward: 0,
    status: "pending",
  },
  {
    id: "q5",
    name: "Shalat Isya",
    category: "deen",
    taskType: "mandatory",
    expReward: 20,
    coinReward: 0,
    status: "pending",
  },
  {
    id: "q6",
    name: "Tilawah 1 halaman",
    category: "deen",
    taskType: "recommended",
    expReward: 30,
    coinReward: 0,
    status: "completed",
  },
  {
    id: "q7",
    name: "Push up 20 reps",
    category: "fitness",
    taskType: "recommended",
    targetValue: 20,
    targetUnit: "reps",
    expReward: 20,
    coinReward: 0,
    status: "completed",
  },
  {
    id: "q8",
    name: "Minum 2000 ml",
    category: "water",
    taskType: "recommended",
    targetValue: 2000,
    targetUnit: "ml",
    expReward: 15,
    coinReward: 0,
    status: "pending",
  },
  {
    id: "q9",
    name: "Catat transaksi harian",
    category: "finance",
    taskType: "recommended",
    expReward: 15,
    coinReward: 0,
    status: "completed",
  },
  {
    id: "q10",
    name: "Dzikir pagi petang",
    category: "deen",
    taskType: "custom",
    expReward: 15,
    coinReward: 0,
    status: "skipped",
  },
];

export const demoTransactions: FinancialTransaction[] = [
  {
    id: "t1",
    type: "income",
    category: "Income utama",
    amount: 2_500_000,
    note: "Uang bulanan",
    transactionDate: "2026-05-01",
  },
  {
    id: "t2",
    type: "expense",
    category: "Makan dan minum",
    amount: 45_000,
    note: "Makan siang",
    transactionDate: "2026-05-01",
  },
  {
    id: "t3",
    type: "expense",
    category: "Transportasi",
    amount: 20_000,
    note: "Ojek kampus",
    transactionDate: "2026-05-01",
  },
  {
    id: "t4",
    type: "expense",
    category: "Ibadah dan sedekah",
    amount: 25_000,
    note: "Sedekah harian",
    transactionDate: "2026-05-01",
  },
];

export const demoBudgets: BudgetItem[] = [
  { category: "Makan dan minum", budget: 1_000_000, spent: 620_000 },
  { category: "Transportasi", budget: 400_000, spent: 350_000 },
  { category: "Pendidikan", budget: 600_000, spent: 250_000 },
  { category: "Ibadah dan sedekah", budget: 300_000, spent: 145_000 },
];

export const demoSavingsGoal: SavingsGoal = {
  name: "Laptop Belajar",
  targetAmount: 9_000_000,
  currentAmount: 3_150_000,
  targetDate: "2026-12-30",
};

export const demoItems: AvatarItem[] = [
  {
    id: "item-1",
    name: "Shadow Cloak",
    itemType: "skin",
    rarity: "rare",
    priceCoin: 120,
    unlockLevel: 10,
    owned: true,
    equipped: true,
  },
  {
    id: "item-2",
    name: "Dawn Seeker Aura",
    itemType: "aura",
    rarity: "epic",
    priceCoin: 260,
    unlockLevel: 18,
    owned: false,
    equipped: false,
  },
  {
    id: "item-3",
    name: "Fajr Guardian Frame",
    itemType: "frame",
    rarity: "common",
    priceCoin: 80,
    unlockLevel: 8,
    owned: true,
    equipped: false,
  },
  {
    id: "item-4",
    name: "Budget Keeper Title",
    itemType: "title",
    rarity: "rare",
    priceCoin: 150,
    unlockLevel: 12,
    owned: true,
    equipped: true,
  },
];

export const demoOnboardingAnswers: OnboardingAnswers = {
  userType: "mahasiswa",
  goals: ["ibadah", "olahraga", "finansial"],
  dailyTimeMinutes: 30,
  pushUpBase: 12,
  squatBase: 20,
  pullUpBase: 2,
  runBaseKm: 1,
  tilawahTarget: "1 halaman",
  waterTargetMl: 2000,
  monthlyIncome: 2_500_000,
};
