export const routes = {
  home: "/",
  login: "/login",
  register: "/register",
  signIn: "/sign-in",
  signUp: "/sign-up",
  dashboard: "/dashboard",
  onboarding: "/onboarding",
  quests: "/quests",
  deen: "/deen",
  fitness: "/fitness",
  water: "/water",
  finance: "/finance",
  planning: "/planning",
  avatar: "/avatar",
  aiCoach: "/ai-coach",
  squad: "/squad",
  history: "/history",
  achievements: "/achievements",
  accessControl: "/access-control",
  admin: "/admin",
  adminAudit: "/admin/audit",
  settings: "/settings",
  health: "/api/health",
} as const;

export const publicRoutePatterns = [
  routes.home,
  `${routes.login}(.*)`,
  `${routes.register}(.*)`,
  `${routes.signIn}(.*)`,
  `${routes.signUp}(.*)`,
  routes.health,
];
